# Generated by Django 4.1.3 on 2022-11-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='catchphrase',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='super',
            name='super_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='super_types.supertype'),
        ),
    ]
