# Generated by Django 4.1.3 on 2022-11-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_alter_super_super_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='catchphrase',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
