# Generated by Django 4.1.3 on 2022-11-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0004_alter_super_catchphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='catchphrase',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
