# Generated by Django 4.1.3 on 2022-11-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0006_alter_super_catchphrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='catchphrase',
            field=models.CharField(default='', max_length=255),
        ),
    ]
